### PR TITLE
Fix the `--typescript` option swallowing the first input after it

### PR DESCRIPTION
**Pull request by Page-**
Previously `resin-lint --typescript src test` would only recognise `test` as a target directory

Change-type: patch

### CODE REVIEW

**Comment by Page-** [comment]
@LucianBuzzo can you publish this (unless auto-publishing is set up?)

**Comment by zvin** [comment]
This was a major change, not patch.

**Comment by LucianBuzzo** [comment]
@Page- It appears that this module auto publishes https://www.npmjs.com/package/resin-lint

**Comment by Page-** [comment]
@zvin the major change was https://github.com/resin-io/node-resin-lint/pull/15
@LucianBuzzo it does now because I PRed it in https://github.com/resin-io/node-resin-lint/pull/19 but it didn't before

**Comment by zvin** [comment]
@Page- #15 is a patch too.
Some projects are relying on the first argument behind `--typescript` being swallowed (like here https://github.com/resin-io-modules/file-disk/blob/master/package.json#L24 ).
This PR changed the `resin-lint` command interface.
It doesn't matter much as `resin-lint` is only a dev dependency and the projects will get fixed.

**Pull request merged**
